# Generated by Django 5.1.2 on 2024-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('politics', 'Politics'), ('sports', 'Sports'), ('entertainment', 'Entertainment')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
