# Generated by Django 5.1.2 on 2024-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the advertisement', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the ad', null=True, upload_to='advertisements/')),
                ('video_url', models.URLField(blank=True, help_text='Add a YouTube video URL', null=True)),
                ('link', models.URLField(blank=True, help_text="Link to the advertisement's website", null=True)),
                ('description', models.TextField(blank=True, help_text='Description or details about the ad', null=True)),
            ],
        ),
    ]
